Friends_SocialMedia_UI/ViewModels/Home/PostCommentVM.cs
namespace Friends_SocialMedia_UI.ViewModels.Home
{
    public class PostCommentVM
    {
        public int PostId { get; set; }
        public string Content { get; set; }
    }
}

Friends_SocialMedia_UI/ViewModels/Home/PostDeleteVM.cs
namespace Friends_SocialMedia_UI.ViewModels.Home
{
    public class PostDeleteVM
    {
        public int PostId { get; set; }
    }
}

Friends_SocialMedia_UI/ViewModels/Home/PostFavoriteVM.cs
namespace Friends_SocialMedia_UI.ViewModels.Home
{
    public class PostFavoriteVM
    {
        public int PostId { get; set; }
    }
}

Friends_SocialMedia_UI/ViewModels/Home/PostLikeVM.cs
namespace Friends_SocialMedia_UI.ViewModels.Home
{
    public class PostLikeVM
    {
        public int PostId { get; set; }
    }
}

Friends_SocialMedia_UI/ViewModels/Home/PostReportVM.cs
namespace Friends_SocialMedia_UI.ViewModels.Home
{
    public class PostReportVM
    {
        public int PostId { get; set; }
    }
}

Friends_SocialMedia_UI/ViewModels/Home/PostVM.cs
namespace Friends_SocialMedia_UI.ViewModels.Home
{
    public class PostVM
    {
        public string Content { get; set; }
    }
}

Friends_SocialMedia_UI/ViewModels/Home/PostVisibilityVM.cs
namespace Friends_SocialMedia_UI.ViewModels.Home
{
    public class PostVisibilityVM
    {
        public int PostId { get; set; }
    }
}

Friends_SocialMedia_UI/ViewModels/Home/RemoveCommentVM.cs
namespace Friends_SocialMedia_UI.ViewModels.Home
{
    public class RemoveCommentVM
    {
        public int CommentId { get; set; }
        public int PostId { get; set; }
    }
}

Friends_SocialMedia_UI/Controllers/HomeController.cs
using Friends_Data.Data.Models;
using Friends_Data.Helpers.Concerns;
using Friends_Data.Helpers.Constants;
using Friends_Data.Helpers.Enums;
using Friends_Data.Services;
using Friends_SocialMedia_UI.Controllers.Base;
using Friends_SocialMedia_UI.ViewModels.Home;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Friends_SocialMedia_UI.Controllers
{
    [Authorize(Roles = AppRole.User)]
    public class HomeController : BaseController
    {
        private readonly IPostService _postService;
        private readonly IHashtagService _hashtagService;
        private readonly IFilesService _fileService;
        private readonly INotificationsService _notificationsService;

        public HomeController(IPostService postService, IHashtagService hashtagService,
            IFilesService filesService, INotificationsService notificationsService)
        {
            _postService = postService;
            _hashtagService = hashtagService;
            _fileService = filesService;
            _notificationsService = notificationsService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var loggedInUserId = GetUserId();
            if (loggedInUserId == null) return RedirectToLogin();

            var allPosts = await _postService.GetAllPostsAsync(loggedInUserId.Value);
            return View(allPosts);
        }

        public async Task<IActionResult> GetPosById(int postId)
        {
            var post = await _postService.GetPostByIdAsync(postId);
            return View("Details", post);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(PostVM post)
        {
            //Get the logged in user
            var loggedInUserId = GetUserId();
            if (loggedInUserId == null) return RedirectToLogin();

            var imageUploadPath = await _fileService.UploadImageAsync(post.Image, ImageFileType.PostImage);

            var newPost = new Post()
            {
                Content = post.Content,
                DateCreated = DateTime.UtcNow,
                DateUpdated = DateTime.UtcNow,
                ImageUrl = imageUploadPath,
                NoOfReports = 0,
                UserId = loggedInUserId.Value
            };

            await _postService.CreatePostAsync(newPost);
            await _hashtagService.AddPostHashTagsAsync(post.Content);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TogglePostLike(PostLikeVM postLikeVM)
        {
            var loggedInUserId = GetUserId();

            if (loggedInUserId == null) return RedirectToLogin();

            var result = await _postService.TogglePostLikeAsync(postLikeVM.PostId, loggedInUserId.Value);
            var post = await _postService.GetPostByIdAsync(postLikeVM.PostId);

            if (result.SendNotification && loggedInUserId != post.UserId) await SendNotification(post.UserId, NotificationTypes.Like, postLikeVM.PostId);
      
            return PartialView("Home/_Post", post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPostComment(PostCommentVM postCommentVM)
        {
            var loggedInUserId = GetUserId();
            if (loggedInUserId == null) return RedirectToLogin();

            //Create a new comment
            var newComment = new Comment()
            {
                UserId = loggedInUserId.Value,
                PostId = postCommentVM.PostId,
                Content = postCommentVM.Content,
                DateCreated = DateTime.UtcNow,
                DateUpdated = DateTime.UtcNow
            };

            await _postService.AddPostCommentAsync(newComment);
            var post = await _postService.GetPostByIdAsync(postCommentVM.PostId);

            if (loggedInUserId != post.UserId)
            {
                await SendNotification(post.UserId, NotificationTypes.Comment, postCommentVM.PostId);
            }

            return PartialView("Home/_Post", post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemovePostComment(RemoveCommentVM removeCommentVM)
        {
            await _postService.RemovePostCommentAsync(removeCommentVM.CommentId);

            var post = await _postService.GetPostByIdAsync(removeCommentVM.PostId);
            return PartialView("Home/_Post", post);
        }

        [HttpPost]
        public async Task<IActionResult> TogglePostFavorite(PostFavoriteVM postFavoriteVM)
        {
            var loggedInUserId = GetUserId();
            if (loggedInUserId == null) return RedirectToLogin();

            var result = await _postService.TogglePostFavoriteAsync(postFavoriteVM.PostId, loggedInUserId.Value);
            var post = await _postService.GetPostByIdAsync(postFavoriteVM.PostId);

            if (result.SendNotification && loggedInUserId != post.UserId) await SendNotification(post.UserId, NotificationTypes.Favorite, postFavoriteVM.PostId);
            return PartialView("Home/_Post", post);
        }

        [HttpPost]
        public async Task<IActionResult> TogglePostVisibility(PostVisibilityVM postVisibilityVM)
        {
            var loggedInUserId = GetUserId();
            if (loggedInUserId == null) return RedirectToLogin();

            await _postService.TogglePostVisibilityAsync(postVisibilityVM.PostId, loggedInUserId.Value);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> AddPostReport(PostReportVM postReportVM)
        {
            var loggedInUserId = GetUserId();
            if (loggedInUserId == null) return RedirectToLogin();

            await _postService.ReportPostAsync(postReportVM.PostId, loggedInUserId.Value);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeletePost(PostDeleteVM postDeleteVM)
        {
            var postRemoved = await _postService.RemovePostAsync(postDeleteVM.PostId);
            await _hashtagService.RemovePostHashTagsAsync(postRemoved.Content);
            return RedirectToAction("Index");
        }

        public async Task SendNotification(int userId, string notificationType, int postId)
        {
            var userFullName = GetUserFullName();
            await _notificationsService.AddNewNotificationAsync(userId, notificationType, userFullName, postId);
        }
    }
}

Friends_SocialMedia_UI/ViewComponent/HastagsViewComponent.cs
using Friends_Data.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Friends_SocialMedia_UI.ViewComponent
{
    public class HastagsViewComponent : Microsoft.AspNetCore.Mvc.ViewComponent
    {
        private readonly AppDbContext _context;
        private readonly ILogger<HastagsViewComponent> _logger;

        public HastagsViewComponent(AppDbContext context, ILogger<HastagsViewComponent> logger)
        {
            _context = context;
            _logger = logger;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var oneWeekAgoNow = DateTime.UtcNow.AddDays(-7);

            var top3Hasttags = await _context.Hastags
                .Where(h => h.DateCreated >= oneWeekAgoNow)
                .OrderByDescending(n => n.Count)
                .Take(3).ToListAsync();
            return View(top3Hasttags);
        }
    }
}

Friends_SocialMedia_UI/ViewComponent/StoriesViewComponent.cs
using Friends_Data.Services;
using Microsoft.AspNetCore.Mvc;

namespace Friends_SocialMedia_UI.ViewComponent
{
    public class StoriesViewComponent : Microsoft.AspNetCore.Mvc.ViewComponent
    {
        private readonly IStoriesService _storiesService;

        public StoriesViewComponent(IStoriesService storiesService)
        {
            _storiesService = storiesService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var allStories =  await _storiesService.GetAllStroiesAsync();
            return View(allStories);
        }
    }
}

Friends_SocialMedia_UI/ViewComponent/SuggestedFriendsViewComponent.cs
using System.Security.Claims;
using Friends_Data.Services;
using Friends_UI.ViewModels.Friends;
using Microsoft.AspNetCore.Mvc;

namespace Friends_UI.ViewComponent
{
    public class SuggestedFriendsViewComponent : Microsoft.AspNetCore.Mvc.ViewComponent
    {
        private readonly IFriendsService _friendsService;

        public SuggestedFriendsViewComponent(IFriendsService friendsService)
        {
            _friendsService = friendsService;   
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var loggedInUserId = ((ClaimsPrincipal)User).FindFirstValue(ClaimTypes.NameIdentifier);
            var suggestedFriends = await _friendsService.GetSuggestedFriendsAsync(int.Parse(loggedInUserId));
            var suggestedFriendsVM = suggestedFriends.Select(n => new UserWithFriendsCountDtoVM()
            {
                UserId = n.User.Id,
                FullName = n.User.FullName,
                ProfilePictureUrl = n.User.ProfilePictureUrl,
                FriendsCount = n.FriendsCount
            }).ToList();
            return View(suggestedFriendsVM);
        }
    }
}

Friends_SocialMedia_UI/Views/Home/Details.cshtml
@model Post

<main id="site__main" class="2xl:ml-[--w-side]  xl:ml-[--w-side-sm] p-2.5 h-[calc(100vh-var(--m-top))] mt-[--m-top]">
    <div class="w-full h-full" id="js-oversized">
        <div class="w-full h-full">
            <partial name="Home/_Post" model="Model" view-data='new ViewDataDictionary(ViewData) {{ "ShowAllComment", false}}' />
        </div>
    </div>
</main>

Friends_SocialMedia_UI/Views/Home/Index.cshtml
@model List<Post>

<main id="site__main" class="2xl:ml-[--w-side]  xl:ml-[--w-side-sm] p-2.5 h-[calc(100vh-var(--m-top))] mt-[--m-top]">
    <div class="lg:flex 2xl:gap-16 gap-12 max-w-[1065px] mx-auto" id="js-oversized">
        <div class="max-w-[680px] mx-auto">

            @await Component.InvokeAsync("Stories")

            <div class="md:max-w-[580px] mx-auto flex-1 xl:space-y-6 space-y-3">
                <div class="bg-white rounded-xl shadow-sm md:p-4 p-2 space-y-4 text-sm font-medium border1">
                    <div class="flex items-center md:gap-3 gap-1">
                        <div class="flex-1 bg-slate-100 hover:bg-opacity-80 transition-all rounded-lg cursor-pointer" uk-toggle="target: #create-status">
                            <div class="py-2.5 text-center">What do you have in mind?</div>
                        </div>
                        <div class="cursor-pointer hover:bg-opacity-80 p-1 px-1.5 rounded-xl transition-all bg-pink-100/60 hover:bg-pink-100" uk-toggle="target: #create-status">
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 stroke-pink-600 fill-pink-200/70" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                <path d="M15 8h.01" />
                                <a href="d:\projects\.net projects\friends_socialmedia\friends_socialmedia_sln\friends_socialmedia_ui\views\home\index.cshtml">d:\projects\.net projects\friends_socialmedia\friends_socialmedia_sln\friends_socialmedia_ui\views\home\index.cshtml</a>
                                <path d="M12 3c7.2 0 9 1.8 9 9s-1.8 9 -9 9s-9 -1.8 -9 -9s1.8 -9 9 -9z" />
                                <path d="M3.5 15.5l4.5 -4.5c.928 -.893 2.072 -.893 3 0l5 5" />
                                <path d="M14 14l1 -1c.928 -.893 2.072 -.893 3 0l2.5 2.5" />
                            </svg>
                        </div>
                    </div>
                </div>

                <div id="posts-container" class="space-y-4">
                    @if (!Model.Any())
                    {
                        <div class="bg-white rounded-xl shadow-sm md:p-4 p-2 space-y-4 text-sm font-medium border1" style="width: 580px;">
                            Currently, there are no posts available. Would you like to create the first one?
                        </div>
                    }
                    else
                    {
                        @foreach (var post in Model)
                        {
                            <partial name="Home/_Post" model="post" view-data='new ViewDataDictionary(ViewData) { { "ShowAllComment", false } }' />
                        }
                    }
                </div>

            </div>
        </div>
        <div class="flex-1">
            <div class="lg:space-y-4 lg:pb-8 max-lg:grid sm:grid-cols-2 max-lg:gap-6">
                <div class="box p-5 px-6 bg-white border-1">
                    @await Component.InvokeAsync("SuggestedFriends")
                </div>
                <div class="box p-5 px-6 bg-white border-1">
                    @await Component.InvokeAsync("Hastags")
                </div>
            </div>
        </div>
    </div>
</main>

<partial name="Modals/_CreateStory" model="new StoryVM()"></partial>
<partial name="Modals/_CreateStatus" model="new PostVM()"></partial>
<partial name="Home/_PostDeleteDialog"></partial>

<script>
        function openPostDeleteConfirmation(postId) {
        document.getElementById('deletConfirmationPostId').value = postId;
        UIkit.modal('#postDeleteDialog').show();
    }

    document.addEventListener('DOMContentLoaded', function() {
        document.getElementById('posts-container').addEventListener('click', function() {

            const button = event.target.closest('.like-button, .favorite-button');

            if(button)
            {
                event.preventDefault();

                var form = button.closest('form');
                var postId = form.querySelector('input[name="postId"]').value;
                var postContainer = document.getElementById('post-' + postId);

                fetch(form.action, {
                    method: 'POST',
                    body: new FormData(form),
                    headers: {}
                }).then(response => response.text())
                  .then(html => {
                      postContainer.innerHTML = html;
                  })
                  .catch(error => console.error('Error: ', error));
            }
        });

        document.getElementById('posts-container').addEventListener('submit', function() {
            var form = event.target;

            if(form.classList.contains('add-post-comment')){
                      event.preventDefault();

                      var postId = form.querySelector('input[name="postId"]').value;
                      var postContainer = document.getElementById('post-' + postId);

                      fetch(form.action, {
                            method: 'POST',
                            body: new FormData(form),
                            headers: {}
                        })
                        .then(response => response.text())
                        .then(html => {
                              postContainer.innerHTML = html;
                        })
                        .catch(error => console.error('Error: ', error));
            }

            if(form.classList.contains('remove-comment-form')){
                    event.preventDefault();

                      var postId = form.querySelector('input[name="postId"]').value;
                      var commentId = form.querySelector('input[name="commentId"]').value;
                      var postContainer = document.getElementById('post-' + postId);

                        fetch(form.action, {
                            method: 'POST',
                            body: new FormData(form),
                            headers: {}
                        })
                        .then(response => response.text())
                        .then(html => {
                              postContainer.innerHTML = html;
                        })
                        .catch(error => console.error('Error: ', error));
            }
        });
    })
</script>