Friends_SocialMedia_UI/Controllers/FriendsController.cs
using Friends_Data.Helpers.Concerns;
using Friends_Data.Helpers.Constants;
using Friends_Data.Services;
using Friends_SocialMedia_UI.Controllers.Base;
using Friends_UI.ViewModels.Friends;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Friends_UI.Controllers
{

    [Authorize(Roles = AppRole.User)]
    public class FriendsController : BaseController
    {
        private readonly IFriendsService _friendsService;
        private readonly INotificationsService _notificationService;

        public FriendsController(IFriendsService friendsService, INotificationsService notificationService)
        {
            _friendsService = friendsService;
            _notificationService = notificationService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = GetUserId();
            if (!userId.HasValue) RedirectToLogin();

            var friendsData = new FriendShipVM()
            {
                Friends = await _friendsService.GetFriendsAsync(userId.Value),
                FriendRequestsSent = await _friendsService.GetSentFriendRequestAsync(userId.Value),
                FriendRequestsReceived = await _friendsService.GetReceivedFriendRequestAsync(userId.Value)
            };

            return View(friendsData);
        }

        [HttpPost]
        public async Task<IActionResult> SendFriendRequest(int receiverId)
        {
            var userId = GetUserId();
            var userFullName = GetUserFullName();

            if (!userId.HasValue)  RedirectToLogin();

            await _friendsService.SendRequestAsync(userId.Value, receiverId);

            await _notificationService.AddNewNotificationAsync(receiverId, NotificationTypes.FriendRequest, userFullName, null);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFriendRequest(int requestId, string status)
        {
            var userId = GetUserId();
            var userFullName = GetUserFullName();

            if (!userId.HasValue) RedirectToLogin();

            var request = await _friendsService.UpdateRequestAsync(requestId, status);

            if (status == FriendShipStatus.Accepted)
            {
                await _notificationService.AddNewNotificationAsync(request.SenderId, NotificationTypes.FriendRequestAccepted, userFullName, null);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFriendRequest(int friendShipId)
        {
            await _friendsService.RemoveFriendAsync(friendShipId);
            return RedirectToAction("Index");
        }
    }
}

Friends_SocialMedia_UI/Controllers/UserController.cs
using Friends_Data.Data.Models;
using Friends_Data.Helpers.Concerns;
using Friends_Data.Services;
using Friends_SocialMedia_UI.Controllers.Base;
using Friends_UI.ViewModels.User;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Friends_UI.Controllers
{
    [Authorize(Roles = AppRole.User)]
    public class UserController : BaseController
    {
        private readonly IUsersService _usersService;
        private readonly UserManager<User> _userManager;

        public UserController(IUsersService usersService, UserManager<User> userManager)
        {
            _usersService = usersService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Details(int userId)
        {
            var allPosts = await _usersService.GetUserPosts(userId);
            var user = await _userManager.FindByIdAsync(userId.ToString());

            var userProfileVM = new GetUserProfileVM()
            {
                User = user,
                Posts = allPosts
            };

            return View(userProfileVM);
        }
    }
}

Friends_SocialMedia_UI/Views/Shared/Components/SuggestedFriends/Default.cshtml
@using Friends_Data.Data.Models
@using Friends_UI.ViewModels.Friends
@model List<UserWithFriendsCountDtoVM>

﻿<div class="flex items-baseline justify-between text-black">
	<div class="font-bold text-base"> People you may know </div>
</div>

<div class="side-list">
	@foreach (var item in Model)
	{
		<div class="side-list-item">
			<a asp-controller="User" asp-action="Details" asp-route-userId="1">
				<img src="@(string.IsNullOrEmpty(item.ProfilePictureUrl) ?
                                Url.Content("~/images/avatar/user.png") :
                                Url.Content(item.ProfilePictureUrl))" class="side-list-image rounded-full" />
			</a>
			<div class="flex-1">
				<a>
					<div class="side-list-title text-black">
						@item.FullName
					</div>
				</a>
				<div class="side-list-info text-black">@item.FriendsCountDisplay</div>
			</div>
			<form asp-controller="Friends" asp-action="SendFriendRequest" method="post">
				<input type="hidden" name="receiverId" value="@item.UserId" />
				<button type="submit" class="button bg-primary-soft text-primary">Follow</button>
			</form>
		</div>
	}
</div>